- name: Start application
  hosts: app
  become: yes
  tasks:

    - name: Install git
      apt: name=git state=present

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle
  
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted