---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
  # Добавим ключ репозитория для последующей работы с ним
  - name: Add APT key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80 
      id: D68FA50FEA312927

  - name: Add APT repository
    apt_repository:
      filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
      repo: deb [ arch=amd64,arm64 ] http://mirror.yandex.ru/mirrors/repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Update and upgrade apt packages
    apt:
      update_cache: yes

  # Выполним установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
      