---
- name: Configure database server
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod


  handlers: # <-- Добавим блок handlers и задачу

    - name: restart mongod
      service: name=mongod state=restarted


- name: Configure app server
  hosts: app
  tags: app-tag
  become: true
  vars:
   db_host: 10.0.0.35
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu
      

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted


- name: Start application
  hosts: app
  tags: deploy-tag
  become: yes
  tasks:

    - name: Install git
      apt: name=git state=present

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle
  
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
  